# -*- coding: utf-8 -*-
"""Multi_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zv1nmW08H_B8A_zj4mCeb9GL7imPh68_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from mpl_toolkits.mplot3d import Axes3D

df = pd.read_csv('/content/oil_gas_factory.csv')
df=df.head(10)

df

X = df[['Por', 'VR']].values.reshape(-1,2)
Y = df['Prod']

model = linear_model.LinearRegression()

model.fit(X,Y)
predicted = model.predict(X)

print(predicted)

r2 = model.score(X, Y)

print(r2)

plt.style.use('default')

fig = plt.figure(figsize=(12, 4))

ax1 = fig.add_subplot(131, projection='3d')
ax2 = fig.add_subplot(132, projection='3d')
ax3 = fig.add_subplot(133, projection='3d')

axes = [ax1, ax2, ax3]

for ax in axes:
    ax.plot(X[:, 0], X[:, 1], Y, color='k', zorder=15, linestyle='none', marker='o', alpha=0.5)
    ax.scatter(X[:, 0], X[:, 1], predicted, facecolor=(0,0,0,0), s=20, edgecolor='#70b3f0')
    ax.set_xlabel('Porosity (%)', fontsize=12)
    ax.set_ylabel('VR', fontsize=12)
    ax.set_zlabel('Gas Prod. (Mcf/day)', fontsize=12)
    ax.locator_params(nbins=4, axis='x')
    ax.locator_params(nbins=5, axis='x')

fig.suptitle('$R^2 = %.2f$' % r2, fontsize=20)

fig.tight_layout()